#! /usr/bin/env bash
##############################################################################
# 
# Copyright (C) Zenoss, Inc. 2012, all rights reserved.
# 
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
# 
##############################################################################


. $ZENHOME/bin/zenfunctions


DAEMON_CLASS_NAME="rancidd"
DAEMON_NAME="zenrancid"
MYPATH=`python -c "import os.path; print os.path.realpath('$0')"`
THISDIR=`dirname $MYPATH`
PRGHOME=`dirname $THISDIR`
PRGNAME=$DAEMON_CLASS_NAME.py
CFGFILE=$CFGDIR/$DAEMON_NAME.conf

generic "$@"
